=== guojiangFighting/android_reverse/aito_250626/unknown/com/gieseckedevrient/offcard/util/AidNames.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.gi-de.com/offcard/aidnames/1.0"
        xmlns:oan="http://www.gi-de.com/offcard/aidnames/1.0"
        xmlns:oct="http://www.gi-de.com/offcard/commontypes/1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">
  <import namespace="http://www.gi-de.com/offcard/commontypes/1.0" schemaLocation="CommonTypes.xsd"/>
  <!--
  #####################################################################
    Aid-name mapping xml property file        OffCard API Version 1.0
    
    Instance document sample (mandatory namespace decl omitted):
    <AidNames>
      <Aid Name="org.globalplatform">A0 00 00 01 51 00</Aid>
      <Aid Name="visa.openplatform">A0 00 00 00 03 00 00</Aid>
    <AidNames>
  #####################################################################
  -->
  <element name="AidNames">
    <complexType>
      <sequence>
        <element name="Aid" type="oct:AidType" minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
</schema>

=== guojiangFighting/android_reverse/aito_250626/unknown/com/gieseckedevrient/offcard/util/AidNames.xml
<?xml version="1.0" encoding="UTF-8"?>
<AidNames xmlns="http://www.gi-de.com/offcard/aidnames/1.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.gi-de.com/offcard/aidnames/1.0 AidNames.xsd">
<Aid Name="Cashon">D3 92 00 10 61</Aid>
<Aid Name="Cashon">D3 92 00 10 61 2A 0A 01 00 00</Aid>
<Aid Name="CashonNext">A0 00 00 01 42 00 4A 42 41 12</Aid>
<Aid Name="CashonNext">A0 00 00 01 42 00 4A 42 41 12 01</Aid>
<Aid Name="com.gieseckedevrient.applets.ANZGolf">D2 76 00 00 05 AA 04 03 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.ANZGolf.GolfApplet">A0 00 00 01 43 03 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.ANZGolf.GolfApplet">D2 76 00 00 05 AA 04 03 01 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomain">D2 76 00 00 05 AA 04 03 40 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomain">D2 76 00 00 05 AA 05 03 40 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomain.SDApplet">D2 76 00 00 05 AA 04 03 40 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomain.SDApplet">D2 76 00 00 05 AB 04 03 40 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomain.SDApplet">D2 76 00 00 05 AB 05 03 40 01 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainDAP">D2 76 00 00 05 AA 04 03 40 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainDAP.SDApplet">D2 76 00 00 05 AA 04 03 40 01 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainDES">A0 00 00 00 03 53 44</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainDES.GDSecurityDomain201DES">A0 00 00 00 03 53 44 41 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainDES.GDSecurityDomain211DES">A0 00 00 00 03 53 44 41 11</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainDES.GDSecurityDomainDES">A0 00 00 00 03 53 44 41</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainRSA">A0 00 00 00 03 53 50</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainRSA.GDSecurityDomain201RSA">A0 00 00 00 03 53 50 41 01</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainRSA.GDSecurityDomain211RSA">A0 00 00 00 03 53 50 41 11</Aid>
<Aid Name="com.gieseckedevrient.applets.GDSecurityDomainRSA.GDSecurityDomainRSA">A0 00 00 00 03 53 50 41</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M">D2 76 00 00 05 AA 04 03 03 02 02</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M.JavaDC_MCL">D2 76 00 00 05 AA 04 03 03 01 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M.JavaDC_MCL">D2 76 00 00 05 AB 04 03 03 01 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M.JavaDC_MCL">D2 76 00 00 05 AB 04 03 03 02 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M.JavaDC_PSE">D2 76 00 00 05 AB 04 03 03 01 02 02</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M4">D2 76 00 00 05 AA 04 03 03 01 03</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M4.JavaDC_M4">D2 76 00 00 05 AB 04 03 03 01 03 01</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M4.JavaDC_MC4">D2 76 00 00 05 AA 04 03 03 01 03 01</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M4.JavaDC_PSE">D2 76 00 00 05 AA 04 03 03 01 03 02</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaDC_M4.JavaDC_PSE">D2 76 00 00 05 AB 04 03 03 01 03 02</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaStarcos">D2 76 00 00 05 AA 04 03 01 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.JavaStarcos.JavaStarcosApplet">D2 76 00 00 05 AA 04 03 01 01 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.jcpiaApplet">D2 76 00 00 05 AB 04 03 E0 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.MEID_DID">D2 76 00 00 05 AA 04 03 10 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.MEID_DID.DIDApplet">D2 76 00 00 05 AA 04 03 10 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.MEID_PKI.PKIApplet">A0 00 00 01 84 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.MEID_SAM">D2 76 00 00 05 AA 04 03 10 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.MEID_SAM.SAMApplet">D2 76 00 00 05 AA 04 03 10 01 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.MifarePerso">D2 76 00 00 05 AA 05 03 E0 09 01</Aid>
<Aid Name="com.gieseckedevrient.applets.MifarePerso">D2 76 00 00 05 AB 05 03 E0 09 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.Mikey">D2 76 00 00 05 AA 04 03 11 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.Mikey.MikeyApplet">D2 76 00 00 05 AB 04 03 11 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.Mods">D2 76 00 00 05 AA 04 03 01 01 04</Aid>
<Aid Name="com.gieseckedevrient.applets.Mods.Modsapplet">D2 76 00 00 05 AB 04 03 01 01 04 01</Aid>
<Aid Name="com.gieseckedevrient.applets.PKI">D2 76 00 00 05 AA 04 03 04 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.PKI">D2 76 00 00 05 AA 04 03 04 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.PKI.EF_INFO">D2 76 00 00 05 AA 04 03 04 01 01 02</Aid>
<Aid Name="com.gieseckedevrient.applets.PKI.EF_INFO ">D2 76 00 00 05 AA 04 03 04 01 02 02</Aid>
<Aid Name="com.gieseckedevrient.applets.PKI.PKIApplet">D2 76 00 00 05 AA 04 03 04 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.PKI.PKIApplet">D2 76 00 00 05 AA 04 03 04 01 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.PSAM">D2 76 00 00 05 AA 04 03 10 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.PSAM">D2 76 00 00 05 AB 04 03 10 02 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartCL_M.SmartCL_M">D2 76 00 00 05 AB 05 03 03 01 05 01</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartCL_M.SmartCL_PPSE">D2 76 00 00 05 AB 05 03 03 01 05 02</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartDC_L.SmartDC_Lapplet">D2 76 00 00 05 AB 04 03 01 01 03 01</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartDC_M.SmartDC_M">D2 76 00 00 05 AB 04 03 03 01 04 01</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartDC_M.SmartDC_M">D2 76 00 00 05 AB 05 03 03 01 06 01</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartDC_M.SmartDC_PSE">D2 76 00 00 05 AB 04 03 03 01 04 02</Aid>
<Aid Name="com.gieseckedevrient.applets.SmartDC_M.SmartDC_PSE">D2 76 00 00 05 AB 05 03 03 01 06 02</Aid>
<Aid Name="com.gieseckedevrient.applets.SNIDApplet">D2 76 00 00 05 AA 05 03 E0 02 01</Aid>
<Aid Name="com.gieseckedevrient.applets.SNIDApplet">D2 76 00 00 05 AA 05 03 E0 02 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.VSDC">D2 76 00 00 05 AA 04 03 03 01 01</Aid>
<Aid Name="com.gieseckedevrient.applets.VSDC.VSCDApplet">D2 76 00 00 05 AA 04 03 03 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.crs">A0 00 00 01 51 43 52 53</Aid>
<Aid Name="com.gieseckedevrient.crsInterface">D2 76 00 01 18 00 03 FF 34 00 6E 89 AA 00 6F 00</Aid>
<Aid Name="com.gieseckedevrient.javacard.adnutil">D2 76 00 01 18 00 02 FF 49 1F F3 89 00 00 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.aloha">D2 76 00 00 05 AA 05 03 E0 03 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.aloha">D2 76 00 00 05 AB 05 03 E0 03 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.felicadispatcher">D2 76 00 00 05 AA 05 03 E0 08 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.felicadispatcher">D2 76 00 00 05 AB 05 03 E0 08 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.GDSecurityDomain">D2 76 00 00 05 AA 04 03 40 01 03</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.GDSecurityDomain.GDSecurityDomainGen">D2 76 00 00 05 AA 04 03 40 01 03 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.initkeyvault">D2 76 00 00 05 AA 05 03 E0 04 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.initkeyvault">D2 76 00 00 05 AB 05 03 E0 04 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.keycard.KeyCard">D2 76 00 00 05 AA 05 03 E0 06 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.applets.keycard.KeyCard">D2 76 00 00 05 AB 05 03 E0 06 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.bip">D2 76 00 01 18 00 02 FF 49 1F F2 89 BF FF 00 00</Aid>
<Aid Name="com.gieseckedevrient.javacard.connection">D2 76 00 00 05 AA FF CB FE 03 05</Aid>
<Aid Name="com.gieseckedevrient.javacard.idea">D2 76 00 01 18 00 02 00 49 10 02 89 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.initsystem">D2 76 00 00 05 AA FF CA FE 02 03</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.gdtcutil">D2 76 00 00 05 AA 08 02 01 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.ExtCrypto">D2 76 00 00 05 AA 04 03 60 02 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.ExtSha1">D2 76 00 00 05 AA 04 03 60 02 02</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.ExtSystem">D2 76 00 00 05 AA 04 03 60 03 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.patchlib">D2 76 00 00 05 AA 04 03 60 04 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.security">D2 76 00 00 05 AA 04 03 60 05 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.tpm">D2 76 00 00 05 AA 04 03 60 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.libraries.tpmex">D2 76 00 00 05 AA 04 03 60 01 02</Aid>
<Aid Name="com.gieseckedevrient.javacard.omnitel">D2 76 00 01 18 00 02 FF 49 10 04 89 00 00 01 00</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.commonram">D2 76 00 00 05 AA FF CA FE 01 02</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.gdcrypto">D2 76 00 00 05 AA FF CA FE 03 04</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.gdsystem">D2 76 00 00 05 AA FF CA FE 00 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.GDSystem.CardManager">A0 00 00 00 03 00 00 00</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.gpio">D2 76 00 00 05 AA 05 02 60 01 05</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.gpioservices">D2 76 00 00 05 AA 05 02 60 01 04</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.hciapdugate">D2 76 00 00 05 AA 05 02 60 01 02</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.hciservices">D2 76 00 00 05 AA 05 02 60 01 01</Aid>
<Aid Name="com.gieseckedevrient.javacard.os.iccreset">D2 76 00 00 05 AA 05 02 60 01 08</Aid>
