=== guojiangFighting/android_reverse/aito_250626/unknown/com/gieseckedevrient/offcard/gp/card/GpCardTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.gi-de.com/offcard/gpcardtypes/1.0"
        xmlns:ogpct="http://www.gi-de.com/offcard/gpcardtypes/1.0"
        xmlns:oct="http://www.gi-de.com/offcard/commontypes/1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">
  <import namespace="http://www.gi-de.com/offcard/commontypes/1.0" schemaLocation="CommonTypes.xsd"/>
  <!--
  #############################################################################
    GlobalPlatform card types XML property file       OffCard API Version 1.0
    
    Instance document sample (mandatory namespace decl omitted):
    <CardTypes>
      <CardType Id="JavaSimCard" Name="Java SIM card">
        <Info>Combined 3G and GSM phase 2+ JavaCard 2.2</Info>
        <CplcData>
          <Pattern>42 50 00 0X A0 0A</Pattern>
          <Pattern>XX XX XX XX A1 01</Pattern>
        </CplcData>
        <Implementation>
          <IssuerSecurityDomain>
            <Aid>A0 00 00 00 03 00 00 00</Aid>
            <Class>com.gieseckedevrient.offcard.gp.Isd</Class>
          </IssuerSecurityDomain>
          <SecurityDomains>
            <Class>com.gieseckedevrient.offcard.gp.Sd</Class>
          </SecurityDomains>
        </Implementation>
      </CardType>
      ...
    <CardTypes>
  #############################################################################
  -->
  <element name="CardTypes">
    <complexType>
      <sequence>
        <element name="CardType" type="ogpct:GpCardType" minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
  
  <complexType name="GpCardType">
    <sequence>
      <element name="Info" type="string" minOccurs="0"/>
      <element name="CplcData" type="ogpct:GpCardTypeCplcDataType"/>
      <element name="Implementation" type="ogpct:GpCardTypeImplementationType"/>
    </sequence>
    <attribute name="Id" type="token" use="required"/>
    <attribute name="Name" type="string" use="required"/>
  </complexType>

  <complexType name="GpCardTypeCplcDataType">
    <sequence>
      <element name="Pattern" type="oct:EncodingHexUnlimitedByteXPattern" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="GpCardTypeImplementationType">
    <sequence>
      <element name="IssuerSecurityDomain" type="ogpct:GpCardTypeIsdType"/>
      <element name="SecurityDomains" type="ogpct:GpCardTypeSdsType" minOccurs="0"/>
      <element name="CardProperties" type="ogpct:GpCardTypePropertiesType" minOccurs="0"/>
    </sequence>
  </complexType>
  
  <complexType name="GpCardTypeIsdType">
    <sequence>
      <element name="Aid" type="oct:EncodingAidHex"/>
      <element name="Class" type="token"/>
      <element name="Properties" type="ogpct:SdPropertiesType" minOccurs="0"/>
    </sequence>
  </complexType>
  
  <complexType name="GpCardTypePropertiesType">
    <sequence>
      <element name="DesAlgorithmId" type="oct:EncodingHex1Byte" minOccurs="0"/>
    </sequence>
  </complexType>
  
  <complexType name="GpCardTypeSdsType">
    <sequence>
      <element name="Class" type="token"/>
      <element name="Properties" type="ogpct:SdPropertiesType" minOccurs="0"/>
    </sequence>
  </complexType>
  
  <complexType name="SdPropertiesType">
    <sequence>
      <element name="Property" minOccurs="0" maxOccurs="unbounded">
        <complexType>
       	  <simpleContent>
            <extension base="token">
         	  <attribute name="Name" type="string"/>
       		</extension>
       	  </simpleContent>
       	</complexType>
      </element>
    </sequence>
  </complexType>
</schema>

=== guojiangFighting/android_reverse/aito_250626/unknown/com/gieseckedevrient/offcard/gp/card/GpCardTypes.xml
<?xml version="1.0" encoding="UTF-8"?>

<CardTypes xmlns="http://www.gi-de.com/offcard/gpcardtypes/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gi-de.com/offcard/gpcardtypes/1.0 GpCardTypes.xsd">

  <CardType Name="UniverSIM Callisto Pro" Id="UniversimCallistoPro">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2 (U)SIM 32-256k, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A0 0D</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.UniversimJupiterIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.UniversimJupiterSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>
  
  <CardType Name="UniverSIM Draco" Id="UniversimDraco">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1 (U)SIM 128k, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A1 03</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.UniversimDracoIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.UniversimDracoSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>

  <CardType Name="ProxSIM Libra" Id="ProxsimLibra">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1 (U)SIM 128k, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A1 04</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.ProxsimLibraIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.ProxsimLibraSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>
  
  <CardType Id="ProxsimTaurus" Name="ProxSIM Taurus">
    <Info/>
    <CplcData>
      <Pattern>XX XX XX XX A1 05</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.ProxsimLibraIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.ProxsimLibraSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>

  <CardType Name="Sm@rtSIM Avior" Id="SmartsimAvior">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A2 01 XX XX 01 XX</Pattern>
      <Pattern>XX XX XX XX A2 01 XX XX 02 XX</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimAviorIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimAviorSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>
  
  <CardType Name="Sm@rtSIM Argo" Id="SmartsimArgo">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A2 02 XX XX 02 XX</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimAviorIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimAviorSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType> 
     <CardType Name="Sm@rtSIM V3.4" Id="SmartsimV34">
    <Info>Combined 3G and GSM phase 2+ JavaCard 3.0.4, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A2 XX XX XX 03 40</Pattern>   
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV34IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV34SecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>
  <CardType Name="Sm@rtSIM V3.5" Id="SmartsimV35">
    <Info>Combined 3G and GSM phase 2+ JavaCard 3.0.4, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX 00 XX A2 XX XX XX 03 50</Pattern>   
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV34IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV34SecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>        
  <CardType Name="Sm@rtSIM V3.x" Id="SmartsimV3x">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A2 XX XX XX 03 XX</Pattern>
<!--       <Pattern>XX XX XX XX A2 02 XX XX 03 00</Pattern> -->
<!--       <Pattern>XX XX XX XX A2 01 XX XX 03 01</Pattern> -->
<!--       <Pattern>XX XX XX XX A2 01 XX XX 03 20</Pattern> -->
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV30IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV30SecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType> 
  
  <CardType Name="Sm@rtSIM Dragon II" Id="SmartsimDragonII">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A2 05 XX XX 02 00</Pattern>
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV30IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimV30SecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType> 
  
  <CardType Name="Sm@rtSIM CX Leo" Id="SmartsimCxLeo">
    <Info>Combined 3G and GSM phase 2+ JavaCard 2.2.1, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A3 02</Pattern> 
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>   
  
  <CardType Name="Sm@rtSIM CX Scorpius (Step 1)" Id="SmartsimCxScorpiusStep1">
    <Info>Combined 3G and GSM phase 2+ JavaCard 3.0, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A3 01 XX XX 01 00</Pattern> 
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxIssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxSecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType> 
  
  <CardType Name="Sm@rtSIM CX Scorpius (Step 2)" Id="SmartsimCxScorpiusStep2">
    <Info>Combined 3G and GSM phase 2+ JavaCard 3.0.4, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A3 01 XX XX 02 00</Pattern> 
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxS2IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxS2SecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType> 
  
  
  <CardType Name="Sm@rtSIM CX Scorpius (Step 3)" Id="SmartsimCxScorpiusStep3">
    <Info>Combined 3G and GSM phase 2+ JavaCard 3.0.4, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A3 01 XX XX 03 00</Pattern> 
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxS2IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxS2SecurityDomain</Class>
      </SecurityDomains>
    </Implementation>
  </CardType>
  
  <CardType Name="Sm@rtSIM CX Scorpius (Step 4)" Id="SmartsimCxScorpiusStep4">
    <Info>Combined 3G and GSM phase 2+ JavaCard 3.0.4, Giesecke &amp; Devrient</Info>
    <CplcData>
      <Pattern>XX XX XX XX A3 01 XX XX 04 02</Pattern> 
    </CplcData>
    <Implementation>
      <IssuerSecurityDomain>
        <Aid>A0 00 00 00 03 00 00 00</Aid>
        <Class>com.gieseckedevrient.offcard.gp.card.components.SmartsimCxS4IssuerSecurityDomain</Class>
      </IssuerSecurityDomain>
      <SecurityDomains>
